name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  IMAGE_NAME: kb-indexer-cloud-backend
  REPO_NAME: ${{ vars.DOCKER_REPO_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: tar -czh . | docker build - -f src-gen/Dockerfile --tag $REPO_NAME/$IMAGE_NAME:latest
    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Push image to docker hub Container Registry
      run: docker push $REPO_NAME/$IMAGE_NAME
