name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  IMAGE_NAME: kb-indexer-cloud-backend
  REPO_NAME: $DOCKER_REPO_NAME

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file python-flask-server-generated/Dockerfile --tag $IMAGE_NAME:latest
    - name: Push image to docker hub Container Registry
      run: docker push $REPO_NAME/$IMAGE_NAME
